sudo: required
services:
  - docker

before_install:
  - docker build -t slick3gz/docker-react -f Dockerfile.dev .

script:
  - docker run slick3gz/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-east-2"
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-807229620929
  bucket_path: "docker-react"
  on:
    branch: master
 